schemas:
  bootstrap: 8000
  develop: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://study.lndo.site/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
langcode: uk
